backend:
  name: github
  repo: Kristian1913/hugo  # Replace with your GitHub username and repo name
  branch: main  # Or 'master' if your main branch is named master
  login: true

media_folder: 'static/media'
public_folder: '/media'

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/post"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
  # New collection: Pages
  - name: "pages"
    label: "Pages"
    folder: "content/pages"  # Path to the pages folder
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
